//webpack //webpack cli
var webpack = require('webpack');
var path = require('path');

module.exports={
    devtool: 'inline-source-map',
    entry:{
        'index':'./src/index.js'
    },
    output:{
        path:path.resolve(__dirname,'dist'),
        filename:'main.js'
    },
    module:{
        rules:[
            {
                test:/\.js$/,
                exclude:/node_modules/,
                use:'babel-loader'
            }
        ]
    },

    //devserver to serve the application only on development 

    devServer:{
        //those content that are not generated by webpack
        contentBase:path.join(__dirname,"public/"),
        port:3001,

        //HMR reloading
        hot:true,
        publicPath: "http://localhost:3001/dist/"
    }
}